FROM node:24

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend /app
COPY app-config.yaml .

RUN sed -i 's/localhost:3001/backend:3001/g' vite.config.ts

CMD ["npm", "run", "dev", "--", "--host"]
