services:
  backend:
    ports:
      - 3001:3001
    build:
      dockerfile: Dockerfile.backend-dev
    environment:
      - INFERENCE_PROVIDER=ollama
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL_ID=gemma3:4b
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BEDROCK_ROLE_ARN=${AWS_BEDROCK_ROLE_ARN}
      - AWS_BEDROCK_MODEL_ID=${AWS_BEDROCK_MODEL_ID}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
    depends_on:
      - ollama
  frontend:
    ports:
      - 5173:5173
    build:
      dockerfile: Dockerfile.frontend-dev
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: frontend/package.json
        - action: rebuild
          path: frontend/package-lock.json
        - action: rebuild
          path: frontend/vite.config.ts
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
