name: Publish
on:
  schedule:
    - cron: "0 4 * * 2" # Tuesdays at 4am UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        build_tags: [aws, ollama]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate variables
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "repo=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push images
        run: |
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --build-arg BUILD_TAGS="${{ matrix.build_tags }}" \
            --tag ghcr.io/${{ steps.vars.outputs.repo }}/${{ github.event.repository.name }}:${{ matrix.build_tags }}-${{ steps.vars.outputs.date }} \
            --tag ghcr.io/${{ steps.vars.outputs.repo }}/${{ github.event.repository.name }}:${{ matrix.build_tags }} \
            .
